[env]
TERM = "xterm-256color"

[general]
import = [
    "~/.config/alacritty/catppuccin-macchiato.toml"
]

[window]
decorations = "None"
#startup_mode = "SimpleFullscreen"
startup_mode = "Fullscreen"

[font]
normal = { family = "Lilex Nerd Font", style = "Regular" }
size = 16

[mouse]
hide_when_typing = true
